// 领域层公共门面：仅从这里向外暴露稳定 API，后续任务在此追加导出。
export {
  validateNewGameInput,
  type GameTypeId,
  type NarrativeStyle,
  type ContentIntensity,
  type NewGameInput,
  type NewGameInputError,
  type NewGameInputErrorCode,
  type ValidatedNewGameInput,
  type ValidateNewGameInputResult
} from "./newGame";
export {
  CONTENT_BUDGET,
  asGenerationId,
  asLocationId,
  asNpcId,
  asQuestId,
  asItemId,
  asEnemyId,
  asEndingId,
  asFactId,
  asSceneId,
  type GenerationId,
  type LocationId,
  type NpcId,
  type QuestId,
  type ItemId,
  type EnemyId,
  type EndingId,
  type FactId,
  type SceneId,
  type FactSource,
  type LocationKind,
  type MainQuestStage,
  type EnemyTier,
  type StatBlock,
  type ContentBudget,
  type ScenarioBlueprint,
  type ScenarioBlueprintCandidate,
  type WorldDefinition,
  type WorldFact,
  type LocationDefinition,
  type NpcDefinition,
  type QuestDefinition,
  type QuestObjective,
  type QuestOutcome,
  type EnemyTemplate,
  type ItemDefinition,
  type EndingDefinition,
  type EndingRequirement,
  type SceneDefinition,
  type GeneratedPlayerDefinition,
  type WorldDefinitionCandidate,
  type WorldFactCandidate,
  type LocationDefinitionCandidate,
  type NpcDefinitionCandidate,
  type QuestDefinitionCandidate,
  type QuestObjectiveCandidate,
  type QuestOutcomeCandidate,
  type EnemyTemplateCandidate,
  type ItemDefinitionCandidate,
  type EndingDefinitionCandidate,
  type EndingRequirementCandidate,
  type SceneDefinitionCandidate,
  type GeneratedPlayerDefinitionCandidate,
  type GenerationMetadata
} from "./scenarioBlueprint";
export {
  type GameEvent,
  type GameInitializedEvent,
  type LocationObservedEvent,
  type NpcMetEvent,
  type FactDiscoveredEvent
} from "./events";
export {
  type GameState,
  type PlayerState,
  type NpcRuntimeState,
  type QuestStatus,
  type QuestRuntimeState,
  type WorldFactState
} from "./gameState";
