// 领域层公共门面：仅从这里向外暴露稳定 API，后续任务在此追加导出。
export {
  validateNewGameInput,
  type GameTypeId,
  type NarrativeStyle,
  type ContentIntensity,
  type GameLength,
  type NewGameInput,
  type NewGameInputError,
  type NewGameInputErrorCode,
  type ValidatedNewGameInput,
  type ValidateNewGameInputResult
} from "./newGame";
export {
  createBudgetPolicy,
  budgetPolicyOf,
  finalMainActOf,
  LEGACY_BUDGET_POLICY,
  type BudgetPolicy
} from "./budgetPolicy";
export {
  asGenerationId,
  asLocationId,
  asNpcId,
  asQuestId,
  asItemId,
  asEnemyId,
  asEndingId,
  asFactId,
  asSceneId,
  locationScaleOf,
  type GenerationId,
  type LocationId,
  type NpcId,
  type QuestId,
  type ItemId,
  type EnemyId,
  type EndingId,
  type FactId,
  type SceneId,
  type FactSource,
  type LocationKind,
  type LocationScale,
  type MainQuestStage,
  type EnemyTier,
  type StatBlock,
  type ItemCategory,
  type ItemRarity,
  type ItemStatLine,
  type ScenarioBlueprint,
  type ScenarioBlueprintCandidate,
  type WorldDefinition,
  type WorldFact,
  type LocationDefinition,
  type NpcDefinition,
  type QuestDefinition,
  type QuestObjective,
  type QuestOutcome,
  type EnemyTemplate,
  type ItemDefinition,
  type EndingDefinition,
  type EndingRequirement,
  type SceneDefinition,
  type GeneratedPlayerDefinition,
  type WorldDefinitionCandidate,
  type WorldFactCandidate,
  type LocationDefinitionCandidate,
  type NpcDefinitionCandidate,
  type QuestDefinitionCandidate,
  type QuestObjectiveCandidate,
  type QuestOutcomeCandidate,
  type EnemyTemplateCandidate,
  type ItemDefinitionCandidate,
  type EndingDefinitionCandidate,
  type EndingRequirementCandidate,
  type SceneDefinitionCandidate,
  type GeneratedPlayerDefinitionCandidate,
  type GenerationMetadata
} from "./scenarioBlueprint";
export {
  resolveItemPresentation,
  type ItemIconKey,
  type ItemPresentation,
  type ItemPresentationSource
} from "./itemPresentation";
export {
  type GameEvent,
  type GameInitializedEvent,
  type LocationObservedEvent,
  type NpcMetEvent,
  type FactDiscoveredEvent,
  type LocationVisitedEvent,
  type QuestCompletedEvent,
  type QuestUnlockedEvent,
  type ItemObtainedEvent,
  type BattleStartedEvent,
  type BattleRoundResolvedEvent,
  type BattleResolvedEvent,
  type EnemyDefeatedEvent,
  type QuestFailedEvent,
  type EndingReachedEvent,
  type NarrativeChoiceEvent,
  type TownPlanGeneratedEvent,
  type NarrativeScenePresentedEvent,
  type BlueprintExpandedEvent
} from "./events";
export { paginateSpeechText } from "./speechPagination";
export {
  type GameState,
  type PlayerState,
  type NpcRuntimeState,
  type QuestStatus,
  type QuestRuntimeState,
  type WorldFactState,
  type BattleStatus,
  type BattleState,
  type EndingState,
  type TownRuntimeState,
  type TownGenerationState
} from "./gameState";
export {
  type NarrativeRuntimeState,
  type NarrativeMode,
  type NarrativeSceneState,
  type NarrativeChoiceState,
  type NarrativeNpcLineState,
  type NarrativeEmotion,
  type NarrativeGenerationState,
  type PlayerNpcChatState,
  NARRATIVE_EMOTIONS
} from "./narrative";
export {
  STORY_MEMORY_VERSION,
  STORY_MEMORY_RECENT_LIMIT,
  createEmptyStoryMemory,
  storyMemoryOf,
  type StoryPacing,
  type StoryMemoryEntry,
  type NpcContinuityMemory,
  type StoryMemoryState
} from "./storyMemory";
export * from "./townSnapshot";
