// npcMemory facade：NPC 记忆与关系的规则层公开面。
// 3B 的 EntityMutation 只能经由这里调用规则，不得 deep-import 内部文件。
export {
  RELATIONSHIP_COMMITMENT_OP_KINDS,
  RELATIONSHIP_COMMITMENT_TARGETS,
  RELATIONSHIP_SIGNAL_CAPS,
  RELATIONSHIP_SIGNAL_POLICY,
  RELATIONSHIP_STAGE_GATES,
  RELATIONSHIP_STAGE_TRANSITIONS,
  applyRelationshipCommitment,
  applyRelationshipSignal,
  applyRelationshipSignalToComponent,
  findRelationshipEdge,
  isAllowedRelationshipStageTransition,
  mintRelationshipCommitmentId,
  mintRelationshipEvidenceId,
  relationshipStageCandidate,
  resolveRelationshipStage,
  upsertRelationshipEdge,
  type ApplyRelationshipCommitmentInput,
  type ApplyRelationshipCommitmentResult,
  type ApplyRelationshipSignalInput,
  type ApplyRelationshipSignalResult,
  type ApplyRelationshipSignalToComponentInput,
  type ApplyRelationshipSignalToComponentResult,
  type RelationshipCapsCoverageLock,
  type RelationshipCommitmentKind,
  type RelationshipCommitmentOperation,
  type RelationshipCommitmentOpKind,
  type RelationshipCommitmentStatus,
  type RelationshipCommitmentStatusOp,
  type RelationshipCommitmentStatusOpLock,
  type RelationshipCommitmentTarget,
  type RelationshipPolicyErrorCode,
  type RelationshipPromisor,
  type RelationshipDebtDirection,
  type RelationshipSignalCaps,
  type RelationshipSignalCommitmentRule,
  type RelationshipSignalInput,
  type RelationshipSignalRule,
  type RelationshipSignalTableLock,
  type RelationshipTargetId,
} from "./relationshipSignalPolicy";
