// Entity/Component 层的公开面：类型化 store、稳定 ID 核心、固定组件、只读 selector
// 与唯一的 legacy 兼容投影。禁止反向 import worldState.ts。
export type { EntityAlias, EntityCore, EntityId, EntityKind, EntityLifecycle } from "./entityCore";
export type {
  EnemyComponent,
  FactionComponent,
  FactComponent,
  ItemOwner,
  ItemPresentationComponent,
  LocationComponent,
  NpcIdentityComponent,
  NpcInteractionsComponent,
  PlayerKnowledgeComponent,
  PlayerIdentityComponent,
  PossessionComponent,
  PositionComponent,
  QuestComponent,
} from "./entityComponents";
export type {
  EnemyEntityRecord,
  EntityRecord,
  FactionEntityRecord,
  FactEntityRecord,
  ItemEntityRecord,
  LocationEntityRecord,
  NpcEntityRecord,
  PlayerEntityRecord,
  QuestEntityRecord,
} from "./entityRecord";
export {
  FACT_CHANGE_SOURCES,
  NPC_ANCHOR_LIST_MAX,
  NPC_ANCHOR_LIST_MIN,
  NPC_CREATION_TEXT_MAX_LENGTH,
  NPC_GOAL_LIST_MAX,
  NPC_GOAL_LIST_MIN,
  NPC_GOAL_HORIZONS,
  NPC_GOAL_PRIORITIES,
  NPC_GOAL_STATUSES,
  NPC_RELATIONSHIP_SEED_LIST_MAX,
  NPC_RELATIONSHIP_SEED_STANCES,
  NPC_HISTORY_CAP,
  NPC_KNOWLEDGE_CERTAINTIES,
  NPC_KNOWLEDGE_DISCLOSURES,
  NPC_KNOWLEDGE_SOURCE_KINDS,
  NPC_TABOO_LIST_MIN,
  RELATIONSHIP_COMMITMENT_KINDS,
  RELATIONSHIP_DEBT_DIRECTIONS,
  RELATIONSHIP_DEBT_STATUSES,
  RELATIONSHIP_DIMENSION_KEYS,
  RELATIONSHIP_DIMENSION_MAX,
  RELATIONSHIP_DIMENSION_MIN,
  RELATIONSHIP_EVIDENCE_CAP,
  RELATIONSHIP_PROMISE_STATUSES,
  RELATIONSHIP_PROMISORS,
  RELATIONSHIP_SEVERITIES,
  RELATIONSHIP_SIGNALS,
  RELATIONSHIP_SOURCE_KINDS,
  RELATIONSHIP_STAGES,
  RELATIONSHIP_TRENDS,
  compareRelationshipTargetIds,
  parseNpcCreationAnchors,
  parseNpcGoalProposals,
  parseNpcRelationshipSeedProposals,
  validateNpcDynamicState,
  validateNpcHistory,
  validateNpcIdentityAnchors,
  validateNpcKnowledge,
  validateNpcRelationships,
  type DirectedRelationshipEdge,
  type FactChangeSourceTableLock,
  type NpcComponentValidationCode,
  type NpcComponentValidationIssue,
  type NpcDynamicStateComponent,
  type NpcGoal,
  type NpcGoalProposal,
  type NpcGoalHorizon,
  type NpcGoalPriority,
  type NpcGoalStatus,
  type NpcRelationshipSeedProposal,
  type NpcRelationshipSeedStance,
  type NpcHistoryComponent,
  type NpcIdentityAnchors,
  type NpcInteractionKeyLock,
  type NpcKnowledgeCertainty,
  type NpcKnowledgeComponent,
  type NpcKnowledgeDisclosure,
  type NpcKnowledgeEntry,
  type NpcKnowledgeSource,
  type NpcRelationshipComponent,
  type RelationshipCommitment,
  type RelationshipDebtStatus,
  type RelationshipDimensions,
  type RelationshipDimensionKey,
  type RelationshipDimensionKeyLock,
  type RelationshipEvidence,
  type RelationshipPromiseStatus,
  type RelationshipSeverity,
  type RelationshipSignal,
  type RelationshipSource,
  type RelationshipStage,
  type RelationshipTrend,
  type TopicIdFieldLock,
} from "./npcComponents";
export {
  createEntityStore,
  entitiesOfKind,
  EntityStoreInvariantError,
  getEntity,
  parseEntityStore,
  validateEntityStoreProvenance,
  validateEntityStoreStructure,
  type EntityStore,
  type EntityStoreValidationCode,
  type EntityStoreValidationIssue,
  type ParseEntityStoreResult,
} from "./entityStore";
export {
  LEGACY_IMPORT_REASON_KEY,
  importNpcLayers,
  normalizeLegacyNpcEntry,
  normalizeLegacyNpcMemory,
  npcGoalId,
  npcLegacyGoalId,
  projectNpcEntry,
  projectNpcMemory,
  type NpcImportedLayers,
} from "./npcProjection";
export {
  compileEntityStoreFromCompatibilityProjection,
  EntityProjectionInvariantError,
  projectEntityStore,
  validateCompatibilityProjectionInput,
  validateEntityCompatibilityProjection,
  validateEntityReferences,
  type EntityCompatibilityProjection,
  type EntityProjectionIssue,
  type EntityReferenceIssue,
  type EntityReferenceIssueCode,
} from "./entityProjection";

export { canNpcDiscloseFact, hasCommittedConfidentialityPermission, hasCommittedDisclosureToPlayer } from "./npcDisclosure";
