import { describe, expect, it } from "vitest";
import {
  createJourneyGame,
  loadWorldState,
  loadGameRecord,
  loadGameView,
  playIssuedChoice,
  playIssuedTravelToUnvisited,
  advanceScene,
} from "./foundationJourney.testutil";
import {
  validateEntityCompatibilityProjection,
  validateEntityReferences,
  validateEntityStoreStructure,
  type EntityCompatibilityProjection,
} from "@/game/domain/entity";
import { validateWorldStateEntityReferences } from "@/game/domain/worldStateValidation";
import type { WorldState } from "@/game/domain/worldState";
import { commitState } from "@/game/application/stateCommit";

function compatibilityProjectionOf(ws: WorldState): EntityCompatibilityProjection {
  return {
    player: ws.player,
    locations: ws.locations,
    currentLocationId: ws.currentLocationId,
    unlockedLocationIds: ws.unlockedLocationIds,
    visitedLocationIds: ws.visitedLocationIds,
    npcs: ws.npcs,
    items: ws.items,
    inventory: ws.inventory,
    worldFacts: ws.worldFacts,
    quests: ws.quests,
    enemies: ws.enemies,
    defeatedEnemyIds: ws.defeatedEnemyIds,
    factions: ws.factions,
  };
}

function expectEntityWorldConsistent(worldState: WorldState): void {
  expect(validateEntityStoreStructure(worldState.entityStore)).toEqual([]);
  expect(validateEntityReferences(worldState.entityStore)).toEqual([]);
  expect(validateWorldStateEntityReferences(worldState)).toEqual([]);
  expect(validateEntityCompatibilityProjection(worldState.entityStore, compatibilityProjectionOf(worldState))).toEqual([]);
}

describe("entity projection cross-layer journey", () => {
  it("keeps store, projection and reload consistent across 15 CAS turns", async () => {
    const { repo } = await createJourneyGame();
    for (let turn = 0; turn < 15; turn += 1) {
      const current = await repo.repo.getCurrentGame();
      expect(current.ok && current.status === "active").toBe(true);
      if (!current.ok || current.status !== "active") return;
      expectEntityWorldConsistent(current.record.worldState);
      const locationId = current.record.worldState.currentLocationId;
      const saved = await repo.repo.applyState({
        gameId: current.record.gameId,
        expectedRevision: current.record.revision,
        nextWorldState: { ...current.record.worldState, entityStore: current.record.worldState.entityStore },
        nextStoryState: current.record.storyState,
      });
      expect(saved.ok).toBe(true);
      if (!saved.ok) return;
      expect(saved.record.worldState.currentLocationId).toBe(locationId);
      expectEntityWorldConsistent(saved.record.worldState);
      if (turn % 5 === 4) {
        const reloaded = repo.record();
        expect(reloaded).not.toBeNull();
        if (reloaded !== null) {
          repo.restore(JSON.parse(JSON.stringify(reloaded)) as typeof reloaded);
          const world = await loadWorldState(repo.repo);
          expect(world).not.toBeNull();
          if (world !== null) expectEntityWorldConsistent(world);
        }
      }
    }
  });

  it("drives gameplay mutations and asserts entity-world consistency at every step", async () => {
    const { repo, gameId } = await createJourneyGame();

    // Helper: assert consistency after any successful mutation or reload.
    async function assertConsistent(): Promise<void> {
      const ws = await loadWorldState(repo.repo);
      expect(ws).not.toBeNull();
      if (ws !== null) expectEntityWorldConsistent(ws);
    }

    // Helper: reload from serialized record and assert consistency.
    async function reloadAndAssert(): Promise<void> {
      const snapshot = repo.record();
      expect(snapshot).not.toBeNull();
      if (snapshot === null) return;
      repo.restore(JSON.parse(JSON.stringify(snapshot)) as typeof snapshot);
      await assertConsistent();
    }

    // --- Opening / reload ---
    await assertConsistent();
    await reloadAndAssert();

    // Advance opening scene (already generated by createGame).
    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();

    // --- Fixed choice: first NPC dialogue ---
    const firstTalk = await playIssuedChoice(repo.repo, "回应");
    expect(firstTalk.ok).toBe(true);
    await assertConsistent();

    // Advance the pending narrative job created by the formal choice.
    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();

    // --- NPC memory write path: second dialogue ---
    const secondTalk = await playIssuedChoice(repo.repo, "回应");
    expect(secondTalk.ok).toBe(true);
    await assertConsistent();

    // Verify NPC memory grew (interaction history has entries).
    {
      const wsAfterTalk = await loadWorldState(repo.repo);
      expect(wsAfterTalk).not.toBeNull();
      if (wsAfterTalk !== null) {
        const npcWithHistory = wsAfterTalk.npcs.find((npc) => npc.memory.interactionHistory.length > 0);
        expect(npcWithHistory).toBeDefined();
      }
    }

    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();
    await reloadAndAssert();

    // --- Movement to a new location (world delta materializes new entities) ---
    // After two NPC talks the quest should complete and act progression creates
    // a new location via the journey evolution source.
    const travelResult = await playIssuedTravelToUnvisited(repo.repo);
    expect(travelResult.ok).toBe(true);
    await assertConsistent();

    // Verify new location was materialized.
    {
      const wsAfterMove = await loadWorldState(repo.repo);
      expect(wsAfterMove).not.toBeNull();
      if (wsAfterMove !== null) {
        expect(wsAfterMove.locations.length).toBeGreaterThanOrEqual(2);
        expect(wsAfterMove.visitedLocationIds.length).toBeGreaterThanOrEqual(2);
      }
    }

    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();

    // --- NPC talk at new location (new NPC from world delta) ---
    // After travel + advanceScene, the new NPC's talk choice should be available.
    const viewAfterTravel = await loadGameView(repo.repo);
    expect(viewAfterTravel.narrative.npcDialogues.length).toBeGreaterThan(0);
    const newNpcTalk = await playIssuedChoice(repo.repo, "表示支持");
    expect(newNpcTalk.ok).toBe(true);
    await assertConsistent();
    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();

    // Second talk at new location to complete the act quest.
    const newNpcTalk2 = await playIssuedChoice(repo.repo, "回应");
    expect(newNpcTalk2.ok).toBe(true);
    await assertConsistent();
    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();

    // --- Item pickup (obtainable item from world delta) ---
    {
      const view = await loadGameView(repo.repo);
      if (view.obtainableItems.length > 0) {
        const pickup = await playIssuedChoice(repo.repo, "拾取");
        expect(pickup.ok).toBe(true);
        await assertConsistent();

        // Verify item entered inventory.
        const wsAfterPickup = await loadWorldState(repo.repo);
        expect(wsAfterPickup).not.toBeNull();
        if (wsAfterPickup !== null) {
          expect(wsAfterPickup.inventory.length).toBeGreaterThanOrEqual(1);
        }

        expect(await advanceScene(repo.repo)).toBe(true);
        await assertConsistent();
      }
    }

    await reloadAndAssert();

    // --- Battle start ---
    // Capture pre-battle entity store for defeat deep-equality assertion.
    const preBattleRecord = await loadGameRecord(repo.repo);
    expect(preBattleRecord).not.toBeNull();
    if (preBattleRecord === null) return;
    const preBattleEntityStore = preBattleRecord.worldState.entityStore;

    const challengeResult = await playIssuedChoice(repo.repo, "挑战");
    expect(challengeResult.ok).toBe(true);
    await assertConsistent();

    // Verify battle is active.
    {
      const wsBattle = await loadWorldState(repo.repo);
      expect(wsBattle).not.toBeNull();
      if (wsBattle !== null) {
        expect(wsBattle.battle.status).toBe("active");
      }
    }

    // --- Force defeat: lower protagonist HP so the next enemy hit kills player ---
    {
      const battleRecord = await loadGameRecord(repo.repo);
      expect(battleRecord).not.toBeNull();
      if (battleRecord === null) return;
      const battle = battleRecord.worldState.battle;
      if (battle.status !== "active") return;

      // Set protagonist combatant HP to 1 and playerHp to 1 so the next
      // enemy counter-attack triggers defeat.
      const lowHpCombatants = battle.combatants?.map((unit) =>
        unit.side === "allies" ? { ...unit, hp: 1 } : unit,
      );
      const patchedBattle = lowHpCombatants !== undefined
        ? { ...battle, playerHp: 1, combatants: lowHpCombatants }
        : { ...battle, playerHp: 1 };
      const patchedWorld: WorldState = {
        ...battleRecord.worldState,
        battle: patchedBattle,
      };
      const patchResult = await commitState(repo.repo, {
        gameId,
        expectedRevision: battleRecord.revision,
        nextWorldState: patchedWorld,
        nextStoryState: battleRecord.storyState,
      });
      expect(patchResult.ok).toBe(true);
      await assertConsistent();
    }

    // --- Defeat: attack and lose ---
    const defeatAttack = await playIssuedChoice(repo.repo, "攻击");
    expect(defeatAttack.ok).toBe(true);
    await assertConsistent();

    // Verify defeat restored entity store to pre-battle state (deep equality).
    {
      const wsAfterDefeat = await loadWorldState(repo.repo);
      expect(wsAfterDefeat).not.toBeNull();
      if (wsAfterDefeat !== null) {
        expect(wsAfterDefeat.entityStore).toEqual(preBattleEntityStore);
        expect(wsAfterDefeat.battle).toEqual({ status: "idle" });
      }
    }

    await reloadAndAssert();

    // --- Rematch: re-engage the same undefeated enemy and win ---
    const rematchChallenge = await playIssuedChoice(repo.repo, "挑战");
    expect(rematchChallenge.ok).toBe(true);
    await assertConsistent();

    // Drive battle rounds until victory.
    let battleResolved = false;
    for (let round = 0; round < 20; round += 1) {
      const ws = await loadWorldState(repo.repo);
      if (ws === null) break;
      if (ws.battle.status === "resolved") {
        expect(ws.battle.outcome).toBe("victory");
        battleResolved = true;
        break;
      }
      if (ws.battle.status !== "active") break;
      const attackResult = await playIssuedChoice(repo.repo, "攻击");
      expect(attackResult.ok).toBe(true);
      await assertConsistent();
      const afterAttack = await loadWorldState(repo.repo);
      if (afterAttack !== null && afterAttack.defeatedEnemyIds.length > 0) {
        battleResolved = true;
        break;
      }
    }
    expect(battleResolved).toBe(true);
    await assertConsistent();

    // Post-victory: verify enemy is in defeatedEnemyIds.
    {
      const wsAfterWin = await loadWorldState(repo.repo);
      expect(wsAfterWin).not.toBeNull();
      if (wsAfterWin !== null) {
        expect(wsAfterWin.defeatedEnemyIds.length).toBeGreaterThanOrEqual(1);
      }
    }

    expect(await advanceScene(repo.repo)).toBe(true);
    await assertConsistent();
    await reloadAndAssert();
  });
});
